 server:
   port: 8084
 encrypt:
    key: test
 ## Setting logging levels
 logging:
   level:
     org.hibernate.type.descriptor.sql.BasicBinder: trace

 keycloak:
   #   领域名称
   realm: test
   #   Keycloak服务器端URL认证端点
   auth-server-url: http://192.168.134.191:8080/auth
   #   客户端ID
   resource: demo-client
   ssl-required: external
   credentials:
     #     客户端密钥
     secret: 416d8d92-fd62-4613-a6c5-b688e58dbbf9
   use-resource-role-mappings: true
   bearer-only: true