####################################
#   This is the core configuration for a configuration service.
#
#   There are 2 way to load your configuration:
#   - The configuration service loads from your local file system.
#   - The configuration service loads from a git repository. 
#
#   You can use either solution.
####################################

####################################
# 1st way: load from your local system
#
# For search location, you can use absolute path or relative path with classpath
#####################################
spring:
  profiles:
   active:
     - native
     - git
  cloud:
    config:
      server:
        native:
#            Use absolute path
#             searchLocations: file:///Users/wuyichen/Documents/workspace/spring-microservices-in-action/server/config-server/src/resources/config/licensingservice
#            Use relative path with classpath
          searchLocations: classpath:config
        git:
          search-paths: '{application}'
          refreshRate: 60
          ignore-local-ssh-settings: true
          clone-on-start: true
          uri: https://github.com/zhisen-ajex/spring-action2.git/config-centernal
####################################
# 2nd way: load from a git repository
####################################
# spring:
#   cloud:
#     config:
#       server:
#         git:
#           search-paths: config-centernal/'{application}'
#           refreshRate: 60
#           ignore-local-ssh-settings: true
#           clone-on-start: true
#           uri: https://github.com/zhisen-ajex/spring-action2.git
##           公开仓库可以不需要用户名/密码
#           username: zhisen.li@aj-ex.com
#           password: 19970816@lzs
