apiVersion: v1 #版本号,必填
kind: Pod #必填
metadata: # 元数据,必填
  name: string #Pod名称,必填
  namespace: string #Pod 所属的命名空间,必填默认值为 default
  labels: #自定义标签列表
    - name: string
  annotations: #自定义注解列表
    - name: string
spec: #Pod 中容器的详细定义,必填
  containers: #Pod 中的容器列表
    - name: string #容器名称,必填
      image: string #容器的镜像,必填
      #镜像拉取策略，镜像拉取策略，可选值包括： Always Never IfNotPresent, 默认值为 Always
        #(1) Always: 表示每次都尝试亘新拉取镜像．
        #(2) IfNotPresent: 表示如果本地有该镜像，则使用本地的镜像，本地不存在时拉取镜像。
        #(3) Never, 表示仅使用本地镜像。
        #另外，如果包含如下设置，系统则将默认设置imagePul1Policy=Always, 如下所述：
        #(I) 不设置 imagePullPolicy, 也未指定镜像的 tag;
        #(2) 不设置 imagePullPolicy, 镜像 tag latest,
        #(3) 启用了名为 AlwaysPulllmages 的准入控制器(Admission Controller)
      imagePullPolicy: [Always|Never|IfNotPresent]
      command: [String] #容器的启动命令列表,如果不填则使用镜像打包时使用的启动命令列表
      args: [] #容器的启动命令参数列表
      workingDir: string #容器的工作目录
      volumeMounts: #挂载到容器内部的存储卷配置
      - name: string #Pod定义的共享存储卷名称
        mountPath: string #Pod定义的共享存储卷挂载到容器内的绝对路径
        readOnly: boolean #是否为只读模式，默认读写模式
      ports: # 容器需要暴露的端口号列表
      - name: string #端口名称
        containerPort: int #容器需要监听的端口号
        hostPort: int #容器所在主机需要监听的端口，默认与containerPort一致，设置hoostPort时，同一台宿主机将无法启动该容器的第二份副本
        protocol: string #端口协议 TCP UDP，默认TCP
      env: #容器运行前需要设置的环境配置列表
        - name: string #变量名称
          value: string #变量值
      resources: #资源限制和请求设置
        limits: #资源限制设置
          cpu: string
          memory: string
        requests: #资源请求设置
          cpu: string #容器启动的初始可用数量
          memory: string #容器启动的初始可用数量
      securityContext:
        privileged: false
      livenessProbe: #对Pod内各容器健康检查的设置,当探测无响应几次之后，系统将自动重启该容器。可以设置的方法包括exec/httpGet/tcpSocket.对一个容器仅需设置一种健康检查方法
        exec:
          command: [string]
        httpGet:
          path: string
          port: number
          host: string
          scheme: string
          httpHeaders:
          - name: string
            volume: string
        tcpSocket:
          port: number
        initialDelaySeconds: 360 #容器启动后多久开始探测,单位s
        timeoutSeconds: 2 # 表示容器必须在2s内做出相应反馈给probe，否则视为探测失败
        periodSeconds: 30  #探测周期，每30s探测一次,单位s，默认值10s探测一次
        successThreshold: 1 # 连续探测1次成功表示成功
        failureThreshold: 3 # 连续探测3次失败表示失败

      #Always表示一旦不管以何种方式终止运行，kubelet都将重启，OnFailure表示只有Pod以非0退出码(代表容器是异常结束)退出才重启，Nerver表示不再重启该Pod
      restartPolicy: [Always|Never|OnFailure] # Pod的重启策略，Always 、Never |、OnFailure
      nodeSelector: object #设置 Node Label, key:value 格式指定， Pod将被调度到具有这些 Label的Node上
      imagePullSecrets: #pull 像时使用忙 Sec et 名称，以 name·secretkey格式指定
      - name: string #如值为docker-registry-secret
      hostNetwork: false #是否使用主机网络模式，默认值为 false. 设置为true 表示容器使用宿主机网络，不再使用 Docker网桥，该 Pod 将无法在同一台宿主机上启动第2个副本
      volumes: #在该Pod上定义共享存储卷列表
      - name: string
        emptyDir: {}
        hostPath:
          path: string
        secret:
          secretName: string
          items:
          - key: string
            path: string
        configMap:
          name: string
          items:
          - key: string
            path: string




