eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
spring:
  cloud:
    gateway:
#      使网关能够基于向服务发现注册的服务创建路由
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
server:
  port: 8076


management:
  endpoints:
    web:
      exposure:
        include: *